{% set version = "0.5.7" %}

package:
  name: aws-c-s3
  version: {{ version }}

source:
  url: https://github.com/awslabs/aws-c-s3/archive/v{{ version }}.tar.gz
  sha256: 2f2eab9bf90a319030fd3525953dc7ac00c8dc8c0d33e3f0338f2a3b554d3b6a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-s3", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - aws-checksums
    - aws-c-auth
    - aws-c-cal
    - aws-c-common
    - aws-c-http
    - aws-c-io
    - openssl  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-s3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/s3/s3.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\s3\\s3.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-s3.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-s3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 library implementation for communicating with the S3 service.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
