{% set name = "aws-c-s3" %}
{% set version = "0.1.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b898f647eecea98e6c60d4dad90afa070c986786a62caedd7ecda1888f88c8c9
  patches:
    - 0001-Find-LibCrypto-on-Linux.patch

build:
  number: 5
  run_exports:
    - {{ pin_subpackage("aws-c-s3", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-checksums
    - aws-c-auth
    - aws-c-cal
    - aws-c-common
    - aws-c-http
    - aws-c-io
    - openssl  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-s3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/s3/s3.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\s3\\s3.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-s3.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-s3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 library implementation for communicating with the S3 service.

extra:
  recipe-maintainers:
    - xhochy
