schema_version: 1

context:
  version: "0.7.13"

package:
  name: aws-c-s3
  version: ${{ version }}

source:
  url: https://github.com/awslabs/aws-c-s3/archive/v${{ version }}.tar.gz
  sha256: b8aeb26072995f2fd4764c788a09a4498002c3e506ef4c2797c559ab018ae0d3

build:
  number: 1

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-checksums
    - aws-c-auth
    - aws-c-cal
    - aws-c-common
    - aws-c-http
    - aws-c-io
    - if: linux
      then: openssl
  run_exports:
    - ${{ pin_subpackage("aws-c-s3", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libaws-c-s3${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/include/aws/s3/s3.h
      - if: win
        then: if not exist %LIBRARY_INC%\\aws\\s3\\s3.h exit 1
      - if: win
        then: if not exist %PREFIX%\\Library\\bin\\aws-c-s3.dll exit 1

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 library implementation for communicating with the S3 service.
  homepage: https://github.com/awslabs/aws-c-s3

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
